Repository Orange-OpenSource/a11y-guidelines, pull requests merged in 2021-04, with the labels that each got.

#133 Add contribution guide
  CONTRIBUTE.md
Labels: documentation

#142 Prevent GitHub actions from external pull requests
  .github/workflows/main.yml
Labels: CI/CD

#154 Publish the code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#155 Mention Netlify usage
  src/_data/footer.js
  src/_data/navigation.js
  src/_includes/partials/footer.njk
Labels: documentation

#156 Fix broken licence links and typos
  README.md
  src/_includes/partials/licence.njk
  src/en/about.md
  src/fr/a-propos.md
Labels: bug

#163 Add missing Confort+ and Boosted links
  src/en/web/index.md
  src/fr/web/index.md
Labels: bug

#162 fix importantForAccessibility
  src/en/mobile/android/development/vocal-navigation.md
  src/fr/mobile/android/developpement/navigation-vocale.md
Labels: bug

#157 Use shortcode to display the current year instead of hardcode it
  src/en/about.md
  src/fr/a-propos.md
Labels: enhancement
